@CertiBlock.Services.Users.Api_HostAddress = http://localhost:5097
@UsersService_Host = http://localhost:5097

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNmJjODg4MS1hNzg2LTQzMmYtYjVkZS1iY2EwM2Y4MTkzYmEiLCJ1bmlxdWVfbmFtZSI6IjM2YmM4ODgxLWE3ODYtNDMyZi1iNWRlLWJjYTAzZjgxOTNiYSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwibmJmIjoxNzUzNzMyOTU5LCJleHAiOjE3NTM3MzY1NTksImlzcyI6ImNlcnRpQmxvY2staXNzdWVyIiwiYXVkIjoiY2VydGlCbG9jay1hdWRpZW5jZSJ9.Fbe68L0KtIYleUfqQKxGlNHksKcq9Iu4lr7pzMSUQdE
@userId = 3fa85f64-5717-4562-b3fc-2c963f66afa6
@testUserId = 36bc8881-a786-432f-b5de-bca03f8193ba
@pageIndex = 1
@pageSize = 2

### 1. Sign Up - Rejestracja nowego użytkownika
POST {{UsersService_Host}}/users-service/Users/signUp
Content-Type: application/json
Accept: application/json

{
  "userId": "{{userId}}",
  "email": "test2@example.com",
  "password": "SecurePassword123!",
  "role": "User",
  "isActive": true
}

### 2. Sign Up - Admin user
POST {{UsersService_Host}}/users-service/Users/signUp
Content-Type: application/json
Accept: application/json

{
  "userId": "{{testUserId}}",
  "email": "admin@admin.com",
  "password": "AdminPassword123!",
  "role": "Admin",
  "isActive": true
}

### 3. Sign In - Logowanie
POST {{UsersService_Host}}/users-service/Users/signIn
Content-Type: application/json
Accept: application/json

{
  "email": "admin@admin.com",
  "password": "password"
}

### 4. Sign In - Test user
POST {{UsersService_Host}}/users-service/Users/signIn
Content-Type: application/json
Accept: application/json

{
  "email": "test@example.com",
  "password": "SecurePassword123!"
}

### 5. Get My Account - Pobranie danych własnego konta
GET {{UsersService_Host}}/users-service/Users/myAccount
Authorization: Bearer {{access_token}}
Accept: application/json

### 6. Get User by ID - Pobranie użytkownika po ID
GET {{UsersService_Host}}/users-service/Users/{{testUserId}}
Authorization: Bearer {{access_token}}
Accept: application/json

### 7. Get All Users - Lista użytkowników z paginacją
GET {{UsersService_Host}}/users-service/Users?PageIndex={{pageIndex}}&PageSize={{pageSize}}
Authorization: Bearer {{access_token}}
Accept: application/json

### 8. Get All Users - Bez parametrów paginacji
GET {{UsersService_Host}}/users-service/Users
Authorization: Bearer {{access_token}}
Accept: application/json

### 9. Change User Role - Zmiana roli użytkownika
PUT {{UsersService_Host}}/users-service/Users/{{userId}}/changeUserRole
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "userId": "{{userId}}",
  "role": "Admin"
}

### 10. Change User Role - Zmiana z powrotem na User
PUT {{UsersService_Host}}/users-service/Users/{{userId}}/changeUserRole
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "userId": "{{userId}}",
  "role": "User"
}

### 11. Delete User - Usunięcie użytkownika
DELETE {{UsersService_Host}}/users-service/Users/{{userId}}
Authorization: Bearer {{access_token}}
Accept: application/json

### 12. Delete Test Admin User
DELETE {{UsersService_Host}}/users-service/Users/{{testUserId}}
Authorization: Bearer {{access_token}}
Accept: application/json