@CertiBlock.Services.Certificates.Api_HostAddress = http://localhost:5052
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNmJjODg4MS1hNzg2LTQzMmYtYjVkZS1iY2EwM2Y4MTkzYmEiLCJ1bmlxdWVfbmFtZSI6IjM2YmM4ODgxLWE3ODYtNDMyZi1iNWRlLWJjYTAzZjgxOTNiYSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwibmJmIjoxNzU0MDYyNDc2LCJleHAiOjE3NTQwNjYwNzYsImlzcyI6ImNlcnRpQmxvY2staXNzdWVyIiwiYXVkIjoiY2VydGlCbG9jay1hdWRpZW5jZSJ9.oOeGKKyGxN_l1kfdpxOn0558vH1a5ZKrNAdZjlRbQxA

POST {{CertiBlock.Services.Certificates.Api_HostAddress}}/certificate-service/Certificates
Accept: */*
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "ownerName": "Kamil Matusz",
  "title": "Uniwersystet",
  "issuedBy": "Kamil Matusz",
  "issuedDate": "2025-07-31T18:41:26.394Z",
  "blockchain": "polygon"
}